### ISSUE TITLE
yaml.scanner.ScannerError: while scanning a simple key

### ISSUE THREAD

**Issue by ddugovic** [careless25/lichess-uci-bot#15]
```
$ python3 main.py
Traceback (most recent call last):
  File "main.py", line 216, in <module>
    load_config()
  File "main.py", line 207, in load_config
    CONFIG = yaml.load(stream)
  File "/home/turing/.local/lib/python3.5/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/home/turing/.local/lib/python3.5/site-packages/yaml/constructor.py", line 35, in get_single_data
    node = self.get_single_node()
  File "/home/turing/.local/lib/python3.5/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/home/turing/.local/lib/python3.5/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/home/turing/.local/lib/python3.5/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/turing/.local/lib/python3.5/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/home/turing/.local/lib/python3.5/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/home/turing/.local/lib/python3.5/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/home/turing/.local/lib/python3.5/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/home/turing/.local/lib/python3.5/site-packages/yaml/scanner.py", line 159, in fetch_more_tokens
    self.stale_possible_simple_keys()
  File "/home/turing/.local/lib/python3.5/site-packages/yaml/scanner.py", line 289, in stale_possible_simple_keys
    "could not find expected ':'", self.get_mark())
yaml.scanner.ScannerError: while scanning a simple key
  in "./config.yml", line 4, column 1
could not find expected ':'
  in "./config.yml", line 5, column 3
```

config.yml:

```
token: "xxxxxxxxxxxxxxxx"    # lichess OAuth2 Token
url: "https://listage.ovh/"  # lichess base URL

engine {                     # engine settings
  dir: "./engines/"          # dir containing engines, relative to this project
  name: "stockfish"          # binary name of the engine to use
#  weights: "latest.txt"     # only if the engine is lczero
#  threads: 1                # only if the engine is lczero
}

max_concurrent_games: 1      # number of games to play simultaneously
max_queued_challenges: 0     # number of challenges to allow to queue

supported_variants:          # chess variants to accept (http://lichess.org/variant)
  - standard
#  - fromPosition
  - antichess
  - atomic
#  - chess960
  - crazyhouse
  - horde
  - kingOfTheHill
  - racingKings
  - threeCheck

supported_tc:                # time controls to accept
  - ultraBullet
  - bullet
  - blitz
  - rapid
#  - classical
#  - correspondence

supported_modes:             # game modes to accept
  - casual                   # unrated games
  - rated                    # rated games - must comment if the engine doesn't try to win
```

**Comment by Aspiration-to-Stars** [comment]
Yes, getting the same issue.

**Comment by ornicar** [comment]
start again from `config.yml.default`

**Comment by ddugovic** [comment]
```
$ cp config.yml.default config.yml && python3 main.py 
Traceback (most recent call last):
  File "main.py", line 209, in <module>
    load_config()
  File "main.py", line 200, in load_config
    CONFIG = yaml.load(stream)
  File "/home/turing/.local/lib/python3.5/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/home/turing/.local/lib/python3.5/site-packages/yaml/constructor.py", line 35, in get_single_data
    node = self.get_single_node()
  File "/home/turing/.local/lib/python3.5/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/home/turing/.local/lib/python3.5/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/home/turing/.local/lib/python3.5/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/turing/.local/lib/python3.5/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/home/turing/.local/lib/python3.5/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/home/turing/.local/lib/python3.5/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/home/turing/.local/lib/python3.5/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/home/turing/.local/lib/python3.5/site-packages/yaml/scanner.py", line 159, in fetch_more_tokens
    self.stale_possible_simple_keys()
  File "/home/turing/.local/lib/python3.5/site-packages/yaml/scanner.py", line 289, in stale_possible_simple_keys
    "could not find expected ':'", self.get_mark())
yaml.scanner.ScannerError: while scanning a simple key
  in "./config.yml", line 4, column 1
could not find expected ':'
  in "./config.yml", line 5, column 3
```

**Comment by careless25** [comment]
```
engine:                   # engine settings
  dir: "./engines/"         # dir containing engines, relative to this project
  name: "engine_name"        # binary name of the engine to use
#  weights: "latest.txt"     # only if the engine is lczero
#  threads: 1                # only if the engine is lczero
```

Notice I removed `{}` and added `:`

**Comment by gbtami** [comment]
Is there any reason using yaml instead of python built in [configparser](https://docs.python.org/3/library/configparser.html#module-configparser) module?

**Comment by careless25** [comment]
@gbtami No reason. I wasn't aware of configparser and have used yamls before.
