### ISSUE TITLE
error in "with logging_pool..."

### ISSUE THREAD

**Issue by ana-ka** [careless25/lichess-uci-bot#20]
I'm getting

Welcome ana-ka-bot!
Traceback (most recent call last):
  File "main.py", line 220, in <module>
    start(li, user_profile, engine_path, weights_path, cfg.get("threads"))
  File "main.py", line 37, in start
    with logging_pool.LoggingPool(CONFIG['max_concurrent_games']+1) as pool:
AttributeError: __exit__

Can't figure out what the issue might be. :(

**Comment by ana-ka** [comment]
Indeed, that solved it. My bad. Maybe adjust the instructions then to reflect that. pip3 install -r... and python3 main.py worked. Thanks.
